name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: employee_management
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Set up MySQL
      run: |
        sudo mysql -e "CREATE DATABASE employee_management;"
        cp .env.example .env
        php artisan key:generate
        php artisan migrate --env=testing

    - name: Run Unit Tests
      run: php artisan test

    - name: Run frontend build
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Set up PHP'
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: 'Run deployment script'
      run: |
        echo "Deploying to Azure..."
        git pull
        composer install --prefer-dist --no-progress --no-suggest
        npm install
        npm run production
        php artisan migrate --force

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: "Capstone Project BSE4101-24"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

