name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: employee_management
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, mysql

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare .env file
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=employee_management" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h"127.0.0.1" --silent; do
          echo "Waiting for MySQL..."
          sleep 1
        done

    - name: Run database migrations
      run: |
        php artisan key:generate
        php artisan migrate --env=testing

    - name: Run Unit Tests
      run: php artisan test

    - name: Run frontend build
      run: npm run build

    - name: Run PHP Code Sniffer
      run: vendor/bin/phpcs
      
    - name: Run PHPStan
      run: ./tools/phpstan analyse --no-progress --error-format=github
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Set up PHP'
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: 'Run deployment script'
      run: |
        echo "Deploying to Azure..."
        git pull
        composer install --prefer-dist --no-progress --no-suggest
        npm install
        npm run production
        php artisan migrate --force

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: "Capstone Project BSE4101-24"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
