name: Build and deploy PHP app to Azure Web App - Capstoneproject

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Step 3: Cache Composer dependencies for faster builds
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Step 4: Run composer install if composer.json exists
      - name: Install PHP dependencies
        if: ${{ hashFiles('composer.json') }}
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress

      # Step 5: Zip the artifact for deployment
      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      # Step 6: Upload artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT token

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      # Step 2: Unzip artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_482CA67E42744A02BEAF742995D81802 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55A7FBAF40344876971A8FDFFBA244C9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2E9038A26D014FBFBE4ACA72C3C31934 }}

      # Step 4: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Capstoneproject'
          slot-name: 'Production'
          package: .

      # Step 5: Log successful deployment
      - name: Log successful deployment
        if: success()
        run: echo "App successfully deployed" >> deployment.log

      # Step 6: Log failed deployment
      - name: Log failed deployment
        if: failure()
        run: echo "App deployment failed" >> deployment.log
